package character;

public enum Proficiencies 
{
	STRENGTH, DEXTERITY, CONSTITUTION, INTELLIGENCE, WISDOM, CHARISMA, ACROBATICS,
	ANIMAL_HANDLING, ARCANA, ATHLETICS, DECEPTION, HISTORY, INSIGHT, INTIMIDATION,
	INVESTIGATION, MEDICINE, NATURE, PERCEPTION, PERFORMANCE, PERSUASION, RELIGION,
	SLEIGHT_OF_HAND, STEALTH, SURVIVAL,
	
	ALCHEMIST_SUPPLIES, BREWER_SUPPLIES, CALIGRAPHER_SUPPLIES, CARPENTERS_TOOLS, COBBLERS_TOOLS,
	COOKS_UTENSILS, GLASSBLOWERS_TOOLS, JEWLERS_TOOLS, LEATHERWORKERS_TOOLS, MASONS_TOOLS,
	PAINTERS_TOOLS, POTTERS_TOOLS, SMITHS_TOOLS, TINKERS_TOOLS, WEAVERS_TOOLS, WOODCARVERS_TOOLS,
	NAVIGATORS_TOOLS, THEIEVES_TOOLS,
	
	DISGUISE_KIT, FORGERY_KIT, HERBALISM_KIT, POISONERS_KIT,
	
	DICE, CHESS, CARDS, POKER,
	
	BAGPIPES, DRUM, DULCIMER, FLUTE, LUTE, LYRE, HORN, PAN_FLUTE, SHAWM, VIOL,
	
	LIGHT_ARMOR, MEDIUM_ARMOR, HEAVY_ARMOR, SIMPLE_WEAPONS, MARTIAL_WEAPONS, SHIELDS,
	
	HAND_CROSSBOW, LONGSWORD, RAPIER, SHORTSWORD
	
};
